version: '2.2'

services:
  geth:
    # image: ethereum/client-go
    build: .
    restart: always
    command: "--nousb --maxpeers 15 --cache=12288 --cache.gc 5 --cache.database 70 --nat any --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain '*' --rpcvhosts '*' --rpcapi eth,net,web3,txpool --ws --wsaddr 0.0.0.0 --wsport 8546 --wsorigins '*' --wsapi eth,net,web3,txpool --targetgaslimit 900000000000000"
#    environment:
#      VIRTUAL_HOST: example.com
#      LETSENCRYPT_HOST: example.com
#      VIRTUAL_PORT: 8545
    ports:
      - PRIVATE_IP_RPC:8545:8545
      - PRIVATE_IP_WS:8546:8546
      - 30303:30303
    volumes:
      - /data/geth:/root/.ethereum
    stop_grace_period: 4m10s
    stop_signal: SIGINT
    healthcheck:
      test: curl -sS http://localhost:8545 || exit 1
      interval: 5s
      timeout: 10s
      retries: 3

#  # if you want to forward 2 ports from geth container to different domains,
#  # use this container to forward one of them
#  forward:
#    image: ajoergensen/docker-socat
#    environment:
#      TARGET: geth
#      LOCAL_PORT: 8546
#      TARGET_PORT: 5000
#      VIRTUAL_HOST: ws-example.com
#      LETSENCRYPT_HOST: ws-example.com
